//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//
// <copyright file="IArticleRepository.cs">
//        最后生成时间：2018-01-24 11:56
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using Vino.Core.Infrastructure.Data;
using Vino.Core.CMS.Data.Common;
using Vino.Core.CMS.Domain.Entity.Content;

namespace Vino.Core.CMS.Data.Repository.Content
{
    /// <summary>
    /// 文章 仓储接口
    /// </summary>
    public partial interface IArticleRepository : IRepository<Article>
    {
    }

    /// <summary>
    /// 文章 仓储接口实现
    /// </summary>
    public partial class ArticleRepository : BaseRepository<Article>, IArticleRepository
    {
        public ArticleRepository(VinoDbContext dbcontext) : base(dbcontext)
        {
        }
    }
}
