// <auto-generated />
using System;
using Ku.Core.CMS.Data.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ku.Core.CMS.Web.Backend.Migrations
{
    [DbContext(typeof(KuDbContext))]
    [Migration("20180721020701_21")]
    partial class _21
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Communication.Sms", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Content")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Data")
                        .HasMaxLength(512);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Mobile")
                        .HasMaxLength(11);

                    b.Property<long>("SmsTempletId");

                    b.HasKey("Id");

                    b.HasIndex("SmsTempletId");

                    b.ToTable("communication_sms");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Communication.SmsAccount", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsEnable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("ParameterConfig");

                    b.Property<string>("Remarks")
                        .HasMaxLength(200);

                    b.Property<short>("Type");

                    b.HasKey("Id");

                    b.ToTable("communication_sms_account");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Communication.SmsQueue", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("CreateTime");

                    b.Property<DateTime>("ExpireTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Response")
                        .HasMaxLength(2000);

                    b.Property<DateTime?>("SendTime");

                    b.Property<long>("SmsId");

                    b.Property<short>("Status");

                    b.HasKey("Id");

                    b.HasIndex("SmsId");

                    b.ToTable("communication_sms_queue");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Communication.SmsTemplet", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Example")
                        .HasMaxLength(400);

                    b.Property<int>("ExpireMinute");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsEnable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Signature")
                        .HasMaxLength(40);

                    b.Property<long?>("SmsAccountId");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Templet")
                        .HasMaxLength(400);

                    b.Property<string>("TempletKey")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("SmsAccountId");

                    b.ToTable("communication_sms_templet");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Content.Article", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Author")
                        .HasMaxLength(32);

                    b.Property<long>("ColumnId");

                    b.Property<string>("Content");

                    b.Property<short>("ContentType");

                    b.Property<string>("CoverData")
                        .HasMaxLength(512);

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPublished");

                    b.Property<string>("Keyword")
                        .HasMaxLength(256);

                    b.Property<int>("OrderIndex");

                    b.Property<string>("Provenance")
                        .HasMaxLength(64);

                    b.Property<DateTime?>("PublishedTime");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<int>("Visits");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId");

                    b.ToTable("content_article");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Content.Column", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("OrderIndex");

                    b.Property<long?>("ParentId");

                    b.Property<string>("Tag")
                        .HasMaxLength(64);

                    b.Property<string>("Title")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("content_column");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Content.MaskWord", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("CreateTime");

                    b.Property<short>("Level");

                    b.Property<int>("MatchCount");

                    b.Property<string>("Tag")
                        .HasMaxLength(128);

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("content_maskword");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.DataCenter.App", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("AppKey")
                        .HasMaxLength(32);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("DownloadUrl")
                        .HasMaxLength(256);

                    b.Property<string>("IconData")
                        .HasMaxLength(512);

                    b.Property<string>("Intro")
                        .HasMaxLength(500);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<short>("Type");

                    b.HasKey("Id");

                    b.ToTable("datacenter_app");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.DataCenter.AppFeedback", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("AdminRemark")
                        .HasMaxLength(1000);

                    b.Property<long>("AppId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<long?>("ProviderId");

                    b.Property<string>("ProviderName")
                        .HasMaxLength(64);

                    b.Property<DateTime?>("ResolveTime");

                    b.Property<bool>("Resolved");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("datacenter_app_feedback");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.DataCenter.AppVersion", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long>("AppId");

                    b.Property<string>("Content")
                        .HasMaxLength(2000);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("DownLoadUrl")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<bool>("Force");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsEnable");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.ToTable("datacenter_app_version");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.DemoEntity", b =>
                {
                    b.Property<long>("Id");

                    b.Property<bool>("BoolValue");

                    b.Property<string>("Content");

                    b.Property<DateTime>("CreateTime");

                    b.Property<decimal?>("DecimalValue");

                    b.Property<double?>("DoubleValue");

                    b.Property<float>("FloatValue");

                    b.Property<int?>("IntValue");

                    b.Property<bool>("IsDeleted");

                    b.Property<short?>("ShortValue");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<short>("Type");

                    b.HasKey("Id");

                    b.ToTable("demo1");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.Brand", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Intro")
                        .HasMaxLength(1024);

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsEnable");

                    b.Property<string>("Logo")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("mall_brand");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.BrandCategoryRef", b =>
                {
                    b.Property<long>("BrandId");

                    b.Property<long>("ProductCategoryId");

                    b.HasKey("BrandId", "ProductCategoryId");

                    b.ToTable("mall_brand_category_ref");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.DeliveryTemplet", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("ChargeConfig");

                    b.Property<short>("ChargeMode");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("EffectiveTime");

                    b.Property<DateTime?>("ExpireTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsEnable");

                    b.Property<bool>("IsSnapshot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<long?>("OriginId");

                    b.Property<int>("SnapshotCount");

                    b.HasKey("Id");

                    b.ToTable("mall_delivery_templet");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.Order", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("AreaCode")
                        .HasMaxLength(20);

                    b.Property<string>("Consignee")
                        .HasMaxLength(20);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("DeliveryAddress");

                    b.Property<DateTime?>("DeliveryTime");

                    b.Property<decimal>("DiscountAmount");

                    b.Property<decimal>("FreightAmount");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPaid");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20);

                    b.Property<decimal>("PayAmount");

                    b.Property<DateTime?>("PayTime");

                    b.Property<decimal>("ProductAmount");

                    b.Property<DateTime?>("ReceivedTime");

                    b.Property<decimal>("RefundAmount");

                    b.Property<short>("RefundStatus");

                    b.Property<DateTime?>("RefundTime");

                    b.Property<string>("Remark")
                        .HasMaxLength(256);

                    b.Property<short>("Status");

                    b.Property<long?>("UserId");

                    b.Property<string>("UserRemark")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("mall_order");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.OrderProduct", b =>
                {
                    b.Property<long>("Id");

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<long>("OrderId");

                    b.Property<long>("ProductId");

                    b.Property<decimal>("ProductPrice");

                    b.Property<long>("ProductSkuId");

                    b.Property<int>("Qty");

                    b.Property<string>("Remark")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductSkuId");

                    b.ToTable("mall_order_product");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.Payment", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("EffectiveTime");

                    b.Property<DateTime?>("ExpireTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsEnable");

                    b.Property<bool>("IsMobile");

                    b.Property<bool>("IsSnapshot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<long?>("OriginId");

                    b.Property<string>("PaymentConfig");

                    b.Property<short>("PaymentMode");

                    b.Property<int>("SnapshotCount");

                    b.HasKey("Id");

                    b.ToTable("mall_payment");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.Product", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long?>("CategoryId");

                    b.Property<string>("Content");

                    b.Property<short>("ContentType");

                    b.Property<DateTime>("CreateTime");

                    b.Property<DateTime?>("EffectiveTime");

                    b.Property<DateTime?>("ExpireTime");

                    b.Property<string>("ImageData")
                        .HasMaxLength(3000);

                    b.Property<string>("Intro")
                        .HasMaxLength(512);

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSnapshot");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<int>("OrderIndex");

                    b.Property<long?>("OriginId");

                    b.Property<string>("PriceRange")
                        .HasMaxLength(32);

                    b.Property<string>("Properties")
                        .HasMaxLength(2000);

                    b.Property<int>("Sales");

                    b.Property<int>("SnapshotCount");

                    b.Property<short>("Status");

                    b.Property<int>("Stock");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<int>("Visits");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("mall_product");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.ProductCategory", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<long?>("ParentId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("mall_product_category");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.ProductSku", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("CoverImage")
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("GainPoints");

                    b.Property<bool>("IsDeleted");

                    b.Property<decimal>("MarketPrice");

                    b.Property<int>("OrderIndex");

                    b.Property<short>("PointsGainRule");

                    b.Property<decimal>("Price");

                    b.Property<long>("ProductId");

                    b.Property<int>("Sales");

                    b.Property<short>("Status");

                    b.Property<int>("Stock");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("mall_product_sku");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.ProductUnit", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("mall_product_unit");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.MaterialCenter.Picture", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("FileName")
                        .HasMaxLength(128);

                    b.Property<string>("FilePath")
                        .HasMaxLength(256);

                    b.Property<long>("FileSize");

                    b.Property<string>("FileType")
                        .HasMaxLength(20);

                    b.Property<string>("Folder")
                        .HasMaxLength(256);

                    b.Property<bool>("IsCompressed");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPublic");

                    b.Property<string>("Md5Code")
                        .HasMaxLength(32);

                    b.Property<string>("ThumbPath")
                        .HasMaxLength(256);

                    b.Property<string>("Title")
                        .HasMaxLength(128);

                    b.Property<long>("UploadUserId");

                    b.HasKey("Id");

                    b.ToTable("materialcenter_picture");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.System.Function", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("AuthCode")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("HasSub");

                    b.Property<bool>("IsEnable");

                    b.Property<int>("Level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<long?>("ParentId");

                    b.HasKey("Id");

                    b.ToTable("system_function");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.System.Menu", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("AuthCode")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("HasSubMenu");

                    b.Property<string>("Icon")
                        .HasMaxLength(20);

                    b.Property<bool>("IsShow");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("OrderIndex");

                    b.Property<long?>("ParentId");

                    b.Property<string>("Tag")
                        .HasMaxLength(20);

                    b.Property<string>("Url")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("system_menu");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.System.Notice", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Content");

                    b.Property<short>("ContentType");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPublished");

                    b.Property<DateTime?>("PublishedTime");

                    b.Property<int>("StickyNum");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("system_notice");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.System.UserActionLog", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("ActionName")
                        .HasMaxLength(30);

                    b.Property<string>("ActionResult")
                        .HasMaxLength(500);

                    b.Property<string>("ControllerName")
                        .HasMaxLength(30);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Ip")
                        .HasMaxLength(46);

                    b.Property<string>("Method")
                        .HasMaxLength(10);

                    b.Property<string>("Operation")
                        .HasMaxLength(40);

                    b.Property<string>("QueryString")
                        .HasMaxLength(256);

                    b.Property<string>("Url")
                        .HasMaxLength(256);

                    b.Property<string>("UrlReferrer")
                        .HasMaxLength(256);

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256);

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("system_action_log");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.UserCenter.Role", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsEnable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Remarks")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("usercenter_role");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.UserCenter.RoleFunction", b =>
                {
                    b.Property<long>("RoleId");

                    b.Property<long>("FunctionId");

                    b.HasKey("RoleId", "FunctionId");

                    b.HasIndex("FunctionId");

                    b.ToTable("usercenter_role_function");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.UserCenter.User", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<int?>("Factor");

                    b.Property<string>("HeadImage")
                        .HasMaxLength(256);

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsEnable");

                    b.Property<string>("Mobile")
                        .HasMaxLength(11);

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("RealName")
                        .HasMaxLength(20);

                    b.Property<string>("Remarks")
                        .HasMaxLength(200);

                    b.Property<short>("Sex");

                    b.HasKey("Id");

                    b.ToTable("usercenter_user");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.UserCenter.UserAddress", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Address")
                        .HasMaxLength(256);

                    b.Property<string>("AreaCode")
                        .HasMaxLength(20);

                    b.Property<string>("City")
                        .HasMaxLength(40);

                    b.Property<string>("CityCode")
                        .HasMaxLength(20);

                    b.Property<string>("Consignee")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("Default");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Province")
                        .HasMaxLength(40);

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(20);

                    b.Property<string>("Region")
                        .HasMaxLength(40);

                    b.Property<string>("RegionCode")
                        .HasMaxLength(20);

                    b.Property<string>("Street")
                        .HasMaxLength(40);

                    b.Property<string>("StreetCode")
                        .HasMaxLength(20);

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("usercenter_user_address");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.UserCenter.UserPoint", b =>
                {
                    b.Property<long>("Id");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("ExpiredPoints");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Points");

                    b.Property<short>("Type");

                    b.Property<int>("UsablePoints");

                    b.Property<int>("UsedPoints");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("usercenter_user_point");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.UserCenter.UserPointRecord", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("BusDesc")
                        .HasMaxLength(500);

                    b.Property<long>("BusId");

                    b.Property<short>("BusType");

                    b.Property<short>("ChangeType");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<long?>("OperatorId");

                    b.Property<int>("Points");

                    b.Property<long>("UserId");

                    b.Property<long>("UserPointId");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserPointId");

                    b.ToTable("usercenter_user_point_record");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.UserCenter.UserRole", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("usercenter_user_role");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.WeChat.WxAccount", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("AppId")
                        .HasMaxLength(32);

                    b.Property<string>("AppSecret")
                        .HasMaxLength(512);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Image")
                        .HasMaxLength(256);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("OriginalId")
                        .HasMaxLength(50);

                    b.Property<string>("Token")
                        .HasMaxLength(30);

                    b.Property<short>("Type");

                    b.Property<string>("WeixinId")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("wechat_account");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.WeChat.WxMenu", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long>("AccountId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsIndividuation");

                    b.Property<string>("MatchRuleCity")
                        .HasMaxLength(40);

                    b.Property<string>("MatchRuleClient")
                        .HasMaxLength(1);

                    b.Property<string>("MatchRuleCountry")
                        .HasMaxLength(40);

                    b.Property<string>("MatchRuleLanguage")
                        .HasMaxLength(10);

                    b.Property<string>("MatchRuleProvince")
                        .HasMaxLength(40);

                    b.Property<string>("MatchRuleSex")
                        .HasMaxLength(1);

                    b.Property<string>("MatchRuleTagId")
                        .HasMaxLength(20);

                    b.Property<string>("MenuData");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<DateTime?>("PublishTime");

                    b.Property<string>("WxMenuId")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("wechat_menu");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.WeChat.WxQrcode", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long>("AccountId");

                    b.Property<DateTime>("CreateTime");

                    b.Property<long?>("CreateUserId");

                    b.Property<string>("EventKey")
                        .HasMaxLength(64);

                    b.Property<int>("ExpireSeconds");

                    b.Property<bool>("IsDeleted");

                    b.Property<short>("PeriodType");

                    b.Property<string>("Purpose")
                        .HasMaxLength(128);

                    b.Property<int>("ScanCount");

                    b.Property<int>("SceneId");

                    b.Property<short>("SceneType");

                    b.Property<string>("Ticket")
                        .HasMaxLength(256);

                    b.Property<string>("Url")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreateUserId");

                    b.ToTable("wechat_qrcode");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.WeChat.WxUser", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long>("AccountId");

                    b.Property<string>("City")
                        .HasMaxLength(100);

                    b.Property<string>("Country")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("HeadImgUrl")
                        .HasMaxLength(500);

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsSubscribe");

                    b.Property<string>("Language")
                        .HasMaxLength(20);

                    b.Property<string>("NickName")
                        .HasMaxLength(100);

                    b.Property<string>("OpenId")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Province")
                        .HasMaxLength(100);

                    b.Property<string>("Remark")
                        .HasMaxLength(30);

                    b.Property<short>("Sex");

                    b.Property<DateTime?>("SubscribeTime");

                    b.Property<string>("UnionId")
                        .HasMaxLength(64);

                    b.Property<string>("UserTags")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("wechat_user");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.WeChat.WxUserTag", b =>
                {
                    b.Property<long>("Id");

                    b.Property<long>("AccountId");

                    b.Property<int>("Count");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<int>("TagId");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("wechat_user_tag");
                });

            modelBuilder.Entity("Ku.Core.TimedTask.TimedTask", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<bool>("AutoReset");

                    b.Property<DateTime>("BeginTime");

                    b.Property<DateTime>("ExpireTime");

                    b.Property<string>("Identifier")
                        .HasMaxLength(256);

                    b.Property<int>("Interval");

                    b.Property<bool>("IsEnabled");

                    b.Property<string>("Name")
                        .HasMaxLength(64);

                    b.Property<int>("RunTimes");

                    b.HasKey("Id");

                    b.ToTable("TimedTasks");
                });

            modelBuilder.Entity("Ku.Core.TimedTask.TimedTaskLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BeginTime");

                    b.Property<long>("Duration");

                    b.Property<DateTime>("EndTime");

                    b.Property<string>("Result")
                        .HasMaxLength(20);

                    b.Property<string>("TaskId")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TimedTaskLogs");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Communication.Sms", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.Communication.SmsTemplet", "SmsTemplet")
                        .WithMany()
                        .HasForeignKey("SmsTempletId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Communication.SmsQueue", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.Communication.Sms", "Sms")
                        .WithMany()
                        .HasForeignKey("SmsId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Communication.SmsTemplet", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.Communication.SmsAccount", "SmsAccount")
                        .WithMany()
                        .HasForeignKey("SmsAccountId");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Content.Article", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.Content.Column", "Column")
                        .WithMany()
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.DataCenter.AppFeedback", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.DataCenter.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.DataCenter.AppVersion", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.DataCenter.App", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.Order", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.UserCenter.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.OrderProduct", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.Mall.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ku.Core.CMS.Domain.Entity.Mall.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ku.Core.CMS.Domain.Entity.Mall.ProductSku", "ProductSku")
                        .WithMany()
                        .HasForeignKey("ProductSkuId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.Product", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.Mall.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.ProductCategory", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.Mall.ProductCategory", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.Mall.ProductSku", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.Mall.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.System.Menu", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.System.Menu", "Parent")
                        .WithMany("SubMenus")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.System.UserActionLog", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.UserCenter.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.UserCenter.RoleFunction", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.System.Function", "Function")
                        .WithMany()
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.UserCenter.UserAddress", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.UserCenter.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.UserCenter.UserPoint", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.UserCenter.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.UserCenter.UserPointRecord", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.UserCenter.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId");

                    b.HasOne("Ku.Core.CMS.Domain.Entity.UserCenter.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ku.Core.CMS.Domain.Entity.UserCenter.UserPoint", "UserPoint")
                        .WithMany()
                        .HasForeignKey("UserPointId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.UserCenter.UserRole", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.UserCenter.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.WeChat.WxMenu", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.WeChat.WxAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.WeChat.WxQrcode", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.WeChat.WxAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ku.Core.CMS.Domain.Entity.WeChat.WxUser", "CreateUser")
                        .WithMany()
                        .HasForeignKey("CreateUserId");
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.WeChat.WxUser", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.WeChat.WxAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ku.Core.CMS.Domain.Entity.WeChat.WxUserTag", b =>
                {
                    b.HasOne("Ku.Core.CMS.Domain.Entity.WeChat.WxAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
