//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//
// <copyright file="IWxMenuService.cs">
//        最后生成时间：2018-01-28 18:40
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using AutoMapper;
using Vino.Core.Cache;
using Vino.Core.CMS.Data.Common;
using Vino.Core.CMS.Data.Repository.WeChat;

namespace Vino.Core.CMS.Service.WeChat
{
    public partial interface IWxMenuService
    {
    }

    public partial class WxMenuService : BaseService, IWxMenuService
    {
        protected readonly IWxMenuRepository _repository;

        public WxMenuService(VinoDbContext context, ICacheService cache, IMapper mapper, IWxMenuRepository repository)
            : base(context, cache, mapper)
        {
            this._repository = repository;
        }
    }
}
